### ISSUE TITLE
combine_similar pushes operations back up too aggressively

### ISSUE THREAD

**Issue by phofl** [dask-contrib/dask-expr#313]
Combine_similar is currently processing Filters and Projections at once, which leads us to agressively pushing operations up (too aggressively sometimes).

```
df = from_pandas(pd.DataFrame({"a": [1, 2, 3, 4, 5, 6], "b": 1, "c": 2}), npartitions=2)
df = df[df.a > 3]
df = df.replace(5, 4)
df["new"] = df.a + df.b
```

```
Assign: key='new'
  Filter:
    Replace: to_replace=5 value=4
      FromPandas: frame='<pandas>' npartitions=2
    GT: right=3
      Projection: columns='a'
        FromPandas: frame='<pandas>' npartitions=2
  Add:
    Filter:
      Projection: columns='a'
        Replace: to_replace=5 value=4
          FromPandas: frame='<pandas>' npartitions=2
      GT: right=3
        Projection: columns='a'
          FromPandas: frame='<pandas>' npartitions=2
    Filter:
      Projection: columns='b'
        Replace: to_replace=5 value=4
          FromPandas: frame='<pandas>' npartitions=2
      GT: right=3
        Projection: columns='a'
          FromPandas: frame='<pandas>' npartitions=2
```

The filter should stay put here. One potential solution is to do 2 passes, push projections back up and then filters in the second step. There might be other approaches that would work as well (not sure though). cc @rjzamora would be great if you could take a look here as well.
